name: poc
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^9.1.1
  flutter_riverpod: ^2.4.9
  permission_handler: ^11.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  encrypt: ^5.0.3
  http: ^1.2.0
  faker: ^2.1.0
  flutter_dotenv: ^5.1.0
  flash: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: any
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - .envrc
